name: Build for multiple targets

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux-native:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm64]
        llvm_env: ["0", "1"]
        debug_env: ["0", "1"]
        coverage_env: ["0", "1"]
        exclude:
          - debug_env: "1"
            coverage_env: "1"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev pkg-config build-essential clang

      - name: Build
        run: make LLVM=${{ matrix.llvm_env }} DEBUG=${{ matrix.debug_env }} COVERAGE=${{ matrix.coverage_env }}

  alpine-linux:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm64]
        llvm_env: ["0", "1"]
        debug_env: ["0", "1"]
        coverage_env: ["0", "1"]
        exclude:
          - debug_env: "1"
            coverage_env: "1"
    runs-on: ${{ matrix.os }}
    container: alpine:latest
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: apk add --no-cache alpine-sdk libsodium-dev pkgconf clang compiler-rt

      - name: Build
        run: make LLVM=${{ matrix.llvm_env }} DEBUG=${{ matrix.debug_env }} COVERAGE=${{ matrix.coverage_env }}

  freebsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm_env: ["0", "1"]
        debug_env: ["0", "1"]
        coverage_env: ["0", "1"]
        exclude:
          - debug_env: "1"
            coverage_env: "1"
    steps:
      - uses: actions/checkout@v6

      - name: Build in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y libsodium pkgconf gmake gcc clang
          run: |
            gmake LLVM=${{ matrix.llvm_env }} DEBUG=${{ matrix.debug_env }} COVERAGE=${{ matrix.coverage_env }}

  openbsd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm_env: ["1"]
        debug_env: ["0", "1"]
        coverage_env: ["0", "1"]
        exclude:
          - debug_env: "1"
            coverage_env: "1"
    steps:
      - uses: actions/checkout@v6

      - name: Build in OpenBSD VM
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg_add libsodium gmake llvm
          run: |
            gmake LLVM=${{ matrix.llvm_env }} DEBUG=${{ matrix.debug_env }} COVERAGE=${{ matrix.coverage_env }}
